--liquibase formatted sql

--changeset milad:1
create table tree_node (id bigint generated by default as identity, height bigint, left_node_id bigint, name varchar(255), right_node_id bigint, parent_id bigint, root_id bigint, primary key (id));
alter table tree_node add constraint FKood9k50gs7b6esccfmef71wtw foreign key (parent_id) references tree_node;
alter table tree_node add constraint FKowh55v6loq8va4if2inpqmuy5 foreign key (root_id) references tree_node;

--changeset milad:2
INSERT INTO tree_node VALUES
(1,0,1,'A',10,NULL,1),
(2,1,2,'B',7,1,1),
(3,1,8,'C',9,1,1),
(4,2,3,'D',4,2,1),
(5,2,5,'E',6,2,1)