--liquibase formatted sql

--changeset milad:1
create table tree_node (id bigint generated by default as identity, is_root boolean, left_node_id bigint, name varchar(255), parent_id bigint, right_node_id bigint, primary key (id))

--changeset milad:2
INSERT INTO tree_node VALUES
(1,1,1,'A',0,20),
(2,0,2,'B',0,9),
(3,0,3,'C',0,4),
(4,0,5,'D',0,6),
(5,0,7,'E',0,8),
(6,0,10,'F',0,19),
(7,0,11,'G',0,14),
(8,0,12,'H',0,13),
(9,0,15,'M',0,16),
(10,0,17,'N',0,18);